requires = ["tox>=4"]
env_list = ["lint", "type", "3.13", "3.12", "3.11", "3.10", "3.9"]

[env_run_base]
description = "run unit tests"
deps = ["pytest>=5", "pytest-sugar"]
commands = [
    [
        "pytest",
        { replace = "posargs", default = [
            "tests",
        ], extend = true },
    ],
]

[env.lint]
description = "run linters"
skip_install = true
deps = ["black"]
commands = [["black", { replace = "posargs", default = ["."], extend = true }]]

[env.type]
description = "run type checks"
deps = ["mypy"]
commands = [
    [
        "mypy",
        { replace = "posargs", default = [
            "src",
            "tests",
        ], extend = true },
    ],
]
